config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "settings", to: "settings#index"

  resources :exercises do
    post "complete"
  end
  resources :exercise_histories

  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :exercises, dependent: :destroy

  def next_exercises
    exercises
      .left_joins(:exercise_histories)
      .select("exercises.*, MAX(exercise_histories.created_at) as last_completed")
      .group("exercises.id")
      .order(Arel.sql("last_completed ASC NULLS FIRST"))
      .limit(remaining_quality)
  end

  private

  def remaining_quality
    return 0 if quantity.nil? || quantity.zero?
    quantity - recently_completed_exercises.count
  end

  def recently_completed_exercises
    show_exercises_after = Rails.env.development? ? 0.minutes.ago : 2.hours.ago
    exercise_history.where("created_at > ?", show_exercises_after).limit(quantity)
  end

  def exercise_history
    ExerciseHistory.where(exercise: self.exercises).order(created_at: :desc)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to exercises_path, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to exercises_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to exercises_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name, :order, :enabled, :quantity ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= category.order %>
  </p>

  <p>
    <strong>Enabled:</strong>
    <%= category.enabled %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= category.quantity %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :order, style: "display: block" %>
    <%= form.number_field :order %>
  </div>

  <div>
    <%= form.label :enabled, style: "display: block" %>
    <%= form.checkbox :enabled %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>