config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "settings", to: "settings#index"

  resources :exercises do
    post "complete"
  end
  resources :exercise_histories

  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/exercise_history.rb
class ExerciseHistory < ApplicationRecord
  belongs_to :exercise
end

app/controllers/exercise_histories_controller.rb
class ExerciseHistoriesController < ApplicationController
  before_action :set_exercise_history, only: %i[ show edit update destroy ]

  # GET /exercise_histories or /exercise_histories.json
  def index
    @exercise_histories = ExerciseHistory.all
  end

  # GET /exercise_histories/1 or /exercise_histories/1.json
  def show
  end

  # GET /exercise_histories/new
  def new
    @exercise_history = ExerciseHistory.new
  end

  # GET /exercise_histories/1/edit
  def edit
  end

  # POST /exercise_histories or /exercise_histories.json
  def create
    @exercise_history = ExerciseHistory.new(exercise_history_params)

    respond_to do |format|
      if @exercise_history.save
        format.html { redirect_to @exercise_history, notice: "Exercise history was successfully created." }
        format.json { render :show, status: :created, location: @exercise_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercise_histories/1 or /exercise_histories/1.json
  def update
    respond_to do |format|
      if @exercise_history.update(exercise_history_params)
        format.html { redirect_to @exercise_history, notice: "Exercise history was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_histories/1 or /exercise_histories/1.json
  def destroy
    @exercise_history.destroy!

    respond_to do |format|
      format.html { redirect_to exercise_histories_path, status: :see_other, notice: "Exercise history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise_history
      @exercise_history = ExerciseHistory.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def exercise_history_params
      params.expect(exercise_history: [ :exercise_id, :sets, :reps, :weight, :success ])
    end
end

app/helpers/exercise_histories_helper.rb
module ExerciseHistoriesHelper
end

app/views/exercise_histories/_exercise_history.html.erb
<div id="<%= dom_id exercise_history %>">
  <p>
    <strong>Exercise:</strong>
    <%= exercise_history.exercise_id %>
  </p>

  <p>
    <strong>Sets:</strong>
    <%= exercise_history.sets %>
  </p>

  <p>
    <strong>Reps:</strong>
    <%= exercise_history.reps %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= exercise_history.weight %>
  </p>

  <p>
    <strong>Success:</strong>
    <%= exercise_history.success %>
  </p>

</div>

app/views/exercise_histories/_form.html.erb
<%= form_with(model: exercise_history) do |form| %>
  <% if exercise_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercise_history.errors.count, "error") %> prohibited this exercise_history from being saved:</h2>

      <ul>
        <% exercise_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :exercise_id, style: "display: block" %>
    <%= form.text_field :exercise_id %>
  </div>

  <div>
    <%= form.label :sets, style: "display: block" %>
    <%= form.number_field :sets %>
  </div>

  <div>
    <%= form.label :reps, style: "display: block" %>
    <%= form.number_field :reps %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.number_field :weight %>
  </div>

  <div>
    <%= form.label :success, style: "display: block" %>
    <%= form.checkbox :success %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exercise_histories/edit.html.erb
<% content_for :title, "Editing exercise history" %>

<h1>Editing exercise history</h1>

<%= render "form", exercise_history: @exercise_history %>

<br>

<div>
  <%= link_to "Show this exercise history", @exercise_history %> |
  <%= link_to "Back to exercise histories", exercise_histories_path %>
</div>

app/views/exercise_histories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Exercise histories" %>

<h1>Exercise histories</h1>

<div id="exercise_histories">
  <% @exercise_histories.each do |exercise_history| %>
    <%= render exercise_history %>
    <p>
      <%= link_to "Show this exercise history", exercise_history %>
    </p>
  <% end %>
</div>

<%= link_to "New exercise history", new_exercise_history_path %>

app/views/exercise_histories/new.html.erb
<% content_for :title, "New exercise history" %>

<h1>New exercise history</h1>

<%= render "form", exercise_history: @exercise_history %>

<br>

<div>
  <%= link_to "Back to exercise histories", exercise_histories_path %>
</div>

app/views/exercise_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exercise_history %>

<div>
  <%= link_to "Edit this exercise history", edit_exercise_history_path(@exercise_history) %> |
  <%= link_to "Back to exercise histories", exercise_histories_path %>

  <%= button_to "Destroy this exercise history", @exercise_history, method: :delete %>
</div>