config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "settings", to: "settings#index"

  resources :exercises do
    post "complete"
  end
  resources :exercise_histories

  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[ show edit update destroy ]

  # GET /exercises or /exercises.json
  def index
    @categories = Category.order(:order)
    @exercises = Exercise.includes(:category).all
  end

  # GET /exercises/1 or /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises or /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to exercises_path, notice: "Exercise was successfully created." }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1 or /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to exercises_path, notice: "Exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1 or /exercises/1.json
  def destroy
    @exercise.destroy!

    respond_to do |format|
      format.html { redirect_to exercises_path, status: :see_other, notice: "Exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def complete
    @exercise = Exercise.find(params[:exercise_id])
    if progress_weight?
      @exercise.update!(weight: @exercise.weight + @exercise.progression)
    end

    begin
      ExerciseHistory.create!(
        exercise: @exercise,
        sequence_position: completed_sequence_position || 0,
        weight: weight,
        success: true,
        sets: sets,
        reps: reps
      )

      redirect_to root_path, notice: "Exercise completed successfully!"
    rescue ActiveRecord::RecordInvalid => e
      redirect_to root_path, alert: "Failed to save: #{e.record.errors.full_messages.join(', ')}"
    rescue => e
      redirect_to root_path, alert: "An error occurred: #{e.message}"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exercise
    @exercise = Exercise.find(params.expect(:id))
  end

  def completed_sequence_position
    return unless sequence

    @completed_sequence_position ||= begin
      current = @exercise.exercise_histories.last&.sequence_position || 0
      (current + 1) % sequence.length
    end
  end

  def progress_weight?
    return false unless sequence && @exercise.weight&.positive? && @exercise.progression&.positive?

    completed_sequence_position == 0
  end

  def sequence
    return unless scheme && scheme[:sequence].present?

    scheme[:sequence]
  end

  def scheme
    return unless @exercise.lift_scheme.present? && @exercise.lift_scheme != "manual"

    @scheme ||= ExerciseSchemes::SCHEMES[@exercise.lift_scheme.to_sym]
  end

  def sequence_position
    return unless sequence

    @sequence_position ||= begin
      current = @exercise.exercise_histories.last&.sequence_position || 0
      (current + 1) % sequence.length
    end
  end

  def sets
    @exercise.sets || @exercise.calculated_total&.length || 0
  end

  def reps
    @exercise.reps || @exercise.calculated_total&.last&.[](:reps) || 0
  end

  def weight
    @exercise.calculated_total&.last&.[](:weight) || 0
  end

  # Only allow a list of trusted parameters through.
  def exercise_params
    params.require(:exercise).permit(:name, :image, :link, :category_id, :lift_scheme, :weight, :progression, :duration, :reps, :sets, :rest, :description)
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
  def plate_color_class(weight)
    case weight
    when 45 then "text-primary"  # blue
    when 35 then "text-warning"  # yellow
    when 25 then "text-success"  # green
    when 10 then "text-danger"   # red
    when 5  then "text-info"     # light blue
    else "text-secondary"        # grey
    end
  end
end

app/views/exercises/_exercise.html.erb
<div id="<%= dom_id exercise %>">
  <p>
    <strong>Name:</strong>
    <%= exercise.name %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= exercise.image %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= exercise.link %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= exercise.category_id %>
  </p>

  <p>
    <strong>Lift scheme:</strong>
    <%= exercise.lift_scheme %>
  </p>

</div>

app/views/exercises/_form.html.erb
<%= form_with(model: exercise) do |form| %>
  <% if exercise.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, 
                      class: "form-control",
                      rows: 3 %>
  </div>

  <div class="mb-3">
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div class="mb-3">
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div class="mb-3">
  <%= form.label :category_id, class: "form-label" %>
  <%= form.collection_select :category_id,
                           Category.all,
                           :id,
                           :name,
                           { prompt: "Select a category" },
                           class: "form-select" %>
</div>

  <div class="mb-3" data-controller="exercise-form">
    <%= form.label :lift_scheme, style: "display: block" %>
    <%= form.select :lift_scheme,
                  Exercise.lift_schemes.keys.map { |scheme| [scheme.titleize, scheme] },
                  { prompt: "Select exercise scheme" },
                  class: "form-select",
                  data: { action: "change->exercise-form#toggleWeightFields" } %>

    <div data-exercise-form-target="weightFields" class="<%= 'd-none' if form.object.manual? %>">
      <div class="mb-3">
        <%= form.label :weight, style: "display: block" %>
        <%= form.number_field :weight, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :progression, style: "display: block" %>
        <%= form.number_field :progression, class: "form-control" %>
      </div>
    </div>

    <div data-exercise-form-target="manualFields" class="<%= 'd-none' unless form.object.manual? %>">
      <div class="mb-3">
        <%= form.label :sets, style: "display: block" %>
        <%= form.number_field :sets, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :reps, style: "display: block" %>
        <%= form.number_field :reps, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :duration_seconds, style: "display: block" %>
        <%= form.number_field :duration, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :rest_seconds, style: "display: block" %>
        <%= form.number_field :rest, class: "form-control" %>
      </div>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<% content_for :title, "Editing exercise" %>

<h1>Editing exercise</h1>

<%= render "form", exercise: @exercise %>

<br>

<div>
  <%= link_to "Show this exercise", @exercise %> |
  <%= link_to "Back to exercises", exercises_path %>
</div>

app/views/exercises/index.html.erb
<% content_for :title, "Exercises" %>

<h1>Exercises</h1>

<%= link_to "New exercise", new_exercise_path %> |
<%= link_to "New category", new_category_path %>


<div id="exercises" class="container mt-4">
  <% @categories.each do |category| %>
    <div class="category-section mb-4">
      <h2 class="border-bottom pb-2 d-flex justify-content-between align-items-center">
        <%= category.name %>
        <%= link_to edit_category_path(category), class: "btn btn-sm btn-outline-secondary" do %>
          <i class="bi bi-pencil"></i>
        <% end %>
      </h2>
      
      <% if category.enabled? %>
        <p class="text-muted">
          Picks <%= category.quantity %> exercises
        </p>
      <% else %>
        <p class="text-danger">
          Disabled
        </p>
      <% end %>
      
      <div class="row">
        <% category.exercises.each do |exercise| %>
          <div class="col-md-4 mb-3">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= exercise.name %></h5>
                <%= link_to edit_exercise_path(exercise), class: "btn btn-sm btn-primary" do %>
                  <i class="bi bi-pencil"></i> Edit
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        
        <% if category.exercises.empty? %>
          <div class="col">
            <p class="text-muted">No exercises in this category</p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/exercises/new.html.erb
<% content_for :title, "New exercise" %>

<h1>New exercise</h1>

<%= render "form", exercise: @exercise %>

<br>

<div>
  <%= link_to "Back to exercises", exercises_path %>
</div>

app/views/exercises/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exercise %>

<div>
  <%= link_to "Edit this exercise", edit_exercise_path(@exercise) %> |
  <%= link_to "Back to exercises", exercises_path %>

  <%= button_to "Destroy this exercise", @exercise, method: :delete %>
</div>